#!/bin/bash

# this file must be launched by 'source`

if [ -n "$#" ]; then
    for ((i=1;i<=$#;i++)); do
        eval export "$(basename "$0")"_$$_$i="'$'$i"
        #eval eval eval echo "$(basename "$0")"_$$_$i="'$'$(basename "$0")_$$_$i"
    done
fi