#!/bin/bash

function checkParameterExistence() {
    if [ $# -eq 0 ]; then
        exit 1
    fi
    for ((i=1;i<=$#;i++)); do
        if [[ `eval echo '$parameter'$i` = $1 ]]; then
            return 0
        fi
    done
}